
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Provider from "../../components/reactquery";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? ''}>
    <html lang="en" style={{backgroundColor: 'black'}}>
      <body className={inter.className}>
      <Provider>
        {children}
      </Provider>
      </body>
    </html>
  
    </GoogleOAuthProvider>
    
  );
}
